<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Wunderbyte license verification for the AI agent.
 *
 * @package    bookingextension_agent
 * @copyright  2026 Wunderbyte GmbH <info@wunderbyte.at>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace bookingextension_agent\local;

/**
 * License check for the agent, mirroring mod_booking's PRO mechanism.
 *
 * Uses the same key format and crypto as Booking PRO (wb_payment::decryptlicensekey,
 * generated by the wb_license generator). The agent is unlocked by a license whose
 * product token is either 'wbagent' (agent-only) or 'bookingagent' (combined
 * Booking + Agent license). The key is read from the agent's own licensekey setting
 * first; a combined key pasted into Booking's licensekey field also counts.
 *
 * mod_booking is probed at runtime, never imported: the engine also ships as the
 * standalone local_wizard plugin where mod_booking may be absent — without the
 * booking crypto no key can validate, so the engine stays in its unlicensed tier.
 */
class wb_license {
    /** @var string Fully qualified booking class carrying the license crypto (runtime-probed). */
    private const PAYMENT_UTIL = '\\mod_booking\\utils\\wb_payment';

    /** @var string Product token for an agent-only license. */
    public const PRODUCT_AGENT = 'wbagent';

    /**
     * Product token for a combined Booking + Agent license.
     *
     * Mirrors wb_payment::PRODUCT_BOOKING_AGENT as a literal: initializing the constant from the
     * booking class would fatal on class load when mod_booking is not installed. Guarded by a
     * unit test against drift.
     *
     * @var string
     */
    public const PRODUCT_BOOKING_AGENT = 'bookingagent';

    /**
     * Helper function to determine if a valid, unexpired agent license is set.
     *
     * @return bool true if the agent license is valid at current date
     */
    public static function agent_license_is_activated(): bool {
        foreach (self::get_candidate_licensekeys() as $licensekey) {
            if (self::licensekey_activates_agent($licensekey)) {
                return true;
            }
        }

        // Overriding - always use PRO for testing / debugging.
        // Check if Behat OR PhpUnit tests are running.
        if ((defined('BEHAT_SITE_RUNNING') && BEHAT_SITE_RUNNING) || (defined('PHPUNIT_TEST') && PHPUNIT_TEST)) {
            return true;
        }

        return false;
    }

    /**
     * Parse a license key into expiration date, product and agent validity.
     *
     * @param string $licensekey encrypted license key as pasted into the setting
     * @return array{expirationdate: string, product: string, validforagent: bool}
     */
    public static function parse_licensekey_for_agent(string $licensekey): array {
        $payment = self::PAYMENT_UTIL;
        if (!class_exists($payment)) {
            return [
                'expirationdate' => '',
                'product' => '',
                'validforagent' => false,
            ];
        }
        $license = $payment::parse_license_content($payment::decryptlicensekey($licensekey));
        $validproduct = in_array(
            $license['product'],
            [self::PRODUCT_AGENT, self::PRODUCT_BOOKING_AGENT],
            true
        );
        $expirationtimestamp = strtotime($license['expirationdate']);

        return [
            'expirationdate' => $license['expirationdate'],
            'product' => $license['product'],
            'validforagent' => $validproduct && $expirationtimestamp !== false && time() < $expirationtimestamp,
        ];
    }

    /**
     * Collect license key candidates: the agent's own setting first, then Booking's
     * licensekey field (where a combined Booking + Agent key naturally lives).
     *
     * @return string[]
     */
    private static function get_candidate_licensekeys(): array {
        $keys = [];

        $ownkey = trim((string)get_config('bookingextension_agent', 'licensekey'));
        if ($ownkey !== '') {
            $keys[] = $ownkey;
        }

        $bookingkey = trim((string)get_config('booking', 'licensekey'));
        if ($bookingkey !== '') {
            $keys[] = $bookingkey;
        }

        return $keys;
    }

    /**
     * Whether one license key unlocks the agent.
     *
     * @param string $licensekey
     * @return bool
     */
    private static function licensekey_activates_agent(string $licensekey): bool {
        return self::parse_licensekey_for_agent($licensekey)['validforagent'];
    }
}
