"""
Wunderbyte Moodle Trial Key Endpoint
=====================================
Mount this FastAPI router in your existing LiteLLM / FastAPI application.

Requirements
------------
    pip install fastapi httpx litellm

Environment variables expected
--------------------------------
    LITELLM_MASTER_KEY   – your LiteLLM admin key (Bearer token for management API)
    LITELLM_BASE_URL     – base URL of your LiteLLM instance, e.g. https://llm.wunderbyte.at
    TRIAL_BUDGET_USD     – optional, default 2.0  ($ credit for the trial key)
    TRIAL_DAYS           – optional, default 14   (lifetime of the trial key in days)

Deployment
----------
In your main FastAPI app:

    from wunderbyte_trial_endpoint import router as trial_router
    app.include_router(trial_router, prefix="/api")

The Moodle plugin will POST to  POST /api/moodle-trial
"""

import hashlib
import logging
import os
from datetime import datetime, timedelta, timezone

import httpx
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, HttpUrl

logger = logging.getLogger(__name__)

router = APIRouter()

# ---------------------------------------------------------------------------
# Configuration (from environment)
# ---------------------------------------------------------------------------
LITELLM_BASE_URL: str = os.environ.get("LITELLM_BASE_URL", "http://localhost:4000").rstrip("/")
LITELLM_MASTER_KEY: str = os.environ.get("LITELLM_MASTER_KEY", "")
TRIAL_BUDGET_USD: float = float(os.environ.get("TRIAL_BUDGET_USD", "2.0"))
TRIAL_DAYS: int = int(os.environ.get("TRIAL_DAYS", "14"))

# LiteLLM model alias that trial keys are allowed to use.
TRIAL_MODEL_ALIAS: str = os.environ.get("TRIAL_MODEL_ALIAS", "wunderbyte-trial")


# ---------------------------------------------------------------------------
# Request / response schemas
# ---------------------------------------------------------------------------
class TrialRequest(BaseModel):
    wwwroot: HttpUrl        # e.g. "https://learn.example.com"
    nonce: str              # hex string generated by Moodle


class TrialResponse(BaseModel):
    apikey: str
    endpoint: str           # base URL Moodle should use (no trailing slash)
    model: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _site_id(wwwroot: str) -> str:
    """Stable, opaque identifier for a Moodle site derived from its wwwroot."""
    return hashlib.sha256(wwwroot.encode()).hexdigest()[:32]


async def _verify_origin(wwwroot: str, nonce: str) -> bool:
    """
    Back-channel challenge: fetch the Moodle challenge endpoint and check that
    it echoes back the nonce exactly.  This proves the request really originates
    from the declared domain.
    """
    return True  # -- DISABLED FOR TESTING --
    challenge_url = f"{wwwroot.rstrip('/')}/mod/booking/trial_challenge.php"
    try:
        async with httpx.AsyncClient(timeout=10, follow_redirects=True) as client:
            resp = await client.get(challenge_url, params={"token": nonce})
            if resp.status_code != 200:
                logger.warning("Challenge failed for %s: HTTP %s", wwwroot, resp.status_code)
                return False
            echoed = resp.text.strip()
            if echoed != nonce:
                logger.warning(
                    "Nonce mismatch for %s: expected %r, got %r", wwwroot, nonce, echoed
                )
                return False
            return True
    except Exception as exc:
        logger.warning("Challenge request error for %s: %s", wwwroot, exc)
        return False


async def _litellm_headers() -> dict:
    return {
        "Authorization": f"Bearer {LITELLM_MASTER_KEY}",
        "Content-Type": "application/json",
    }


async def _find_existing_key(site_id: str) -> str | None:
    """
    Look for an already-issued trial key for this site in LiteLLM.
    Returns the key string if found, None otherwise.
    """
    try:
        async with httpx.AsyncClient(timeout=10) as client:
            resp = await client.get(
                f"{LITELLM_BASE_URL}/key/list",
                headers=await _litellm_headers(),
                params={"key_alias": f"wunderbyte-trial-{site_id}"},
            )
            resp.raise_for_status()
            keys = resp.json().get("keys", [])
            if keys:
                return keys[0].get("key")
    except Exception as exc:
        logger.warning("Could not query existing keys: %s", exc)
    return None


async def _create_trial_key(site_id: str, wwwroot: str) -> str:
    """
    Create a new time-limited, budget-limited LiteLLM virtual key for the trial.
    The key is tagged with the site identifier so it can be found and revoked later.
    """
    expires_at = (datetime.now(timezone.utc) + timedelta(days=TRIAL_DAYS)).isoformat()

    payload = {
        "key_alias": f"wunderbyte-trial-{site_id}",
        "models": [TRIAL_MODEL_ALIAS],
        "max_budget": TRIAL_BUDGET_USD,
        "budget_duration": f"{TRIAL_DAYS}d",
        "expires": expires_at,
        "metadata": {
            "moodle_site": str(wwwroot),
            "site_id": site_id,
            "trial": True,
        },
        ## "tags": ["moodle-trial"],
    }

    async with httpx.AsyncClient(timeout=15) as client:
        resp = await client.post(
            f"{LITELLM_BASE_URL}/key/generate",
            headers=await _litellm_headers(),
            json=payload,
        )
        resp.raise_for_status()
        return resp.json()["key"]


# ---------------------------------------------------------------------------
# Route
# ---------------------------------------------------------------------------
@router.post("/moodle-trial", response_model=TrialResponse)
async def request_moodle_trial(body: TrialRequest) -> TrialResponse:
    """
    Entry point called by the Moodle mod_booking plugin when an admin clicks
    "Start my free trial".

    Steps
    -----
    1. Validate the nonce via back-channel challenge.
    2. Check if this site already has a trial key.
       - If yes: return an informative error (409-like message in HTTP 200 body
         because Moodle's external API layer doesn't handle non-200 well).
    3. Create a new LiteLLM virtual key scoped to the trial model.
    4. Return the key + endpoint to Moodle.
    """
    wwwroot_str = str(body.wwwroot).rstrip("/")
    site_id = _site_id(wwwroot_str)

    # -- 1. Verify origin --
    origin_ok = await _verify_origin(wwwroot_str, body.nonce)
    if not origin_ok:
        raise HTTPException(
            status_code=403,
            detail=(
                "Could not verify that this request originates from "
                f"{wwwroot_str}. "
                "Make sure the Moodle site is publicly reachable."
            ),
        )

    # -- 2. Duplicate check --
    existing_key = await _find_existing_key(site_id)
    if existing_key:
        # Return a structured error that Moodle will surface as a friendly message.
        raise HTTPException(
            status_code=409,
            detail=(
                "A trial key has already been issued for this site. "
                "Please check your AI provider settings in Moodle "
                "(Site administration → AI → AI providers)."
            ),
        )

    # -- 3. Issue a new key --
    try:
        apikey = await _create_trial_key(site_id, wwwroot_str)
    except httpx.HTTPStatusError as exc:
        logger.error("LiteLLM key creation failed: %s", exc.response.text)
        raise HTTPException(status_code=502, detail="Failed to create trial key in LiteLLM : " + str(LITELLM_BASE_URL))

    logger.info("Issued trial key for site %s (id=%s)", wwwroot_str, site_id)

    return TrialResponse(
        apikey=apikey,
        endpoint=LITELLM_BASE_URL,
        model=TRIAL_MODEL_ALIAS,
    )
